### ISSUE TITLE
Could you explain what does the argument "fold" mean

### ISSUE THREAD

**Issue by lyak1314** [selimsef/dfdc_deepfake_challenge#12]
When I run generate_fold.py,I find the "fold" is alway "0"

                    for k, v in metadata.items():
                        fold = None
                        for i, fold_dirs in enumerate(folds):
                            #if part in fold_dirs:
                                fold = i
                                break
                        assert fold is not None
                        video_id = k[:-4]
                        video_fold[video_id] = fold

I debug this part and find "fold” is alway "0" and then break
Since I can't understand what does "fold" mean,I don't know how to solve it and what is the correct 
could you explain  it in detail? thank you!

**Comment by yuzhoufengg2** [comment]
> Fold is the index of the fold (cross validation). As I decided to use a holdout for validation istead of kfold split the fold number is always 0

Fold is always 0,but when I retrain the model,I can not get the train data, due to _prepare_data method.This is a bug？
![image](https://github.com/selimsef/dfdc_deepfake_challenge/assets/65170657/909ad3dc-d4d3-4b72-bd00-a27baaf25159)
![image](https://github.com/selimsef/dfdc_deepfake_challenge/assets/65170657/1b770cc1-e9bd-4d7d-aae4-34c2ca37d0f4)
